- src/components/Drawer/Drawer.vue
- src/pages/AssetViewPage.stories.ts
- src/pages/AssetViewPage.vue
- src/pages/MetaDataOnlyPage.stories.ts
- src/pages/MetaDataOnlyPage.vue
This adds a story and view for metadata only assets. When an asset is loaded, if no `firstFileHandlerId` is present, the asset it determined to be "meta-data only", and renders the data without a viewer.
The view is minimal. (Once the share and download tools are implemented, we can add those to the bottom or side).
Large screen:
Small screen:
> Detect when asset has metadata only, and render in a Meta Only Page

- src/components/Widget/TextAreaWidget/TextAreaItem.vue
only show toggle button if we've actually truncated. Seems like this just got lost in a refactor. Fixes #36
> Show More Fix

- src/components/Modal/Modal.vue
- src/components/MoreLikeThis/ButtonWithCount.vue
- src/components/MoreLikeThis/CountChip.vue
- src/components/MoreLikeThis/MoreLikeThis.vue
- src/config.ts
- src/types/index.ts
This limits the number of results we show in the More Like This section of the asset panel to an instance configurable number (default 3). If there are more results, users can click "Show More" which will open a modal of all results.
If an instance is configured to with `config.moreLikeThis.maxInlineResults` to be 0, no inline results will be shown and instead the users will just have a button to open More Like This results as a modal.
As discussed, we can hone the design elements for the More Like This section once we work out the components on the search results page. (e.g. Maybe a flatter row style component might look better here than a card.)
> Limit number of  inline results of More Like This section

- src/components/ObjectViewer/ObjectViewer.vue
- src/helpers/useElevatorSessionStorage.ts
The api call to get interstitial text happens when when the EmbedButton is mounted. This adds a `v-if` to the EmbedButton within ObjectView to prevent it from mounting if we're not in embed mode.
> fix: `getInterstitialText()` api call should happen only we're embedding an asset

- src/api/index.ts
- src/components/ActiveFileViewToolbar/MoreFileInfoButton.vue
- This checks that `exif` exists on the meta data before rendering image specific More Info, which fixes an issue where the modal would break with non image metadata.
- For non-images, we just render generic tuples with Key-Value of metadata, which seems good enough for most cases.
Resolves #59
> Fix: More Info doesn't work with non-images

- src/api/index.ts
- src/components/ActiveFileViewToolbar/DownloadFileButton.vue
- src/helpers/getExtensionFromFilename.ts
- src/stores/instanceStore.ts
- src/types/FileDownloadTypes.ts
- src/types/index.ts
Resolves #67 
Download button will now correctly show derivatives available to the user, and the original (if available).
> Fix: correctly show derivatives available for download

- package.json
- src/api/index.ts
- src/components/AppMenu/AppMenu.vue
- src/components/AppMenu/PagesNavSection.vue
- src/components/SanitizedHTML/SanitizedHTML.vue
- src/pages/StaticContentPage/StaticContentPage.vue
- src/router.ts
- src/types/index.ts
- yarn.lock
This adds a new `StaticContentPage` component for rendering static page content in Elevator.
Page content is raw HTML, so this includes a `<SanitizeHTML>` component (lifted from another LATIS project) for cleaning up any markup that may be problematic. Under the hood, this component uses the `dompurify` library.
- The page has some very light formatting, which I'm not sold on – so we can (and probably should) tweak this.
- As is typical with user created content, I noticed a lot of inline styles and non-semantic markup in the HTML. There are pros and cons with stripping out these styles. I've chosen to leave them as-is. 
Currently up: <https://dev.elevator.umn.edu/defaultinstance/page/view/3>
Corresponding Elevator PR: https://github.com/UMN-LATIS/elevator/pull/120
> Add components for rendering static pages like `/page/view/1`

- src/components/SearchBar/SearchBar.vue
- src/pages/SearchPage/SearchPage.vue
- src/stores/searchStore.ts
This resolves:
- #75 
- #76 
These issues were a biproduct of having two different "sources of truth" for the search query: the `searchText` input in the search component and `searchStore.query` in the search store.
This:
- uses `searchStore.query` as the "source of truth" for the search query input and removes the `searchText` ref intermediary
- no longer clears the search query once it's submitted
- switches the search result page header to use `searchEntry.searchText` rather than `searchStore.query` (since searchStoer.query is tied to the input, and not the current results a user may be viewing).
- Shows "All Assets" as a page header if the searchText is empty (and we're not browsing a collection)
Latest up on <http://dev.elevator.umn.edu/defaultinstance>
> fix: persist search input between searches

- src/components/Button/Button.vue
- src/components/PrevNextSearchResultNav/PrevNextSearchResultNav.vue
- src/components/SearchResultCard/SearchResultCard.vue
- src/icons/ChevronLeftIcon.vue
- src/icons/ChevronRightIcon.vue
- src/icons/index.ts
- src/layouts/NoScrollLayout.vue
- src/pages/AssetViewPage/AssetView.vue
- src/pages/AssetViewPage/AssetViewPage.vue
- src/pages/SearchPage/SearchPage.vue
- src/router.ts
- src/stores/searchStore.ts
This adds a navbar with links to the previous and next search result assets on the Asset Page.
Asset page with viewer:
Meta data only page:
This version uses the searchStore for determining the next/prev search results, rather than doing another API query. When the user is within LOAD_MORE_THRESHOLD (currently 5) results of the last loaded result, more will be fetched.
currently up: <https://dev.elevator.umn.edu/defaultinstance/>
Closes #56
> Add navigation for prev/next search results within Asset Page

- src/components/AppMenu/AppMenuItem.vue
Previously, `AppMenuGroup` had a background color, but `AppMenuItem` didn't. Which meant some menu items, like links to "Collections" and static pages had different effects on hover than groups like "Edit" and "Help".
This applies the same styles to `AppMenuItem`.
> add bg to AppMenuItem on hover

- src/components/AppMenu/AppMenu.vue
- src/components/AppMenu/EditNavSection.vue
- src/pages/AssetViewPage/AssetViewPage.vue
When there's no asset loaded in the assetStore, the Edit menu won't appear in the App Menu since this `assetId` is null.
This removes the check for a truthy `assetId` from `<AppMenu>` and instead checks within the `EditNavSection` so that users still have an option to Add Assets or view all their assets if they `canManageAssets`.
> Fix App Menu `Edit` doesn't appear

- src/components/AppHeader/AppHeader.vue
- src/components/AppMenu/AppMenu.vue
- src/components/AppMenu/AppMenuPure.vue
- src/components/AppMenu/EditNavSection.vue
- src/components/AuthDropDown/AuthDropDown.vue
- src/components/Avatar/Avatar.vue
- src/components/DropDown/DropDown.vue
- src/components/InputGroup/InputGroup.vue
- src/components/SearchBar/SearchBar.vue
- src/components/ThemeSelector/ThemeSelector.vue
- src/pages/AssetViewPage/AssetViewPage.vue
Resolves:
- #101 
- #85 
This updates the app header:
- moves the Theme selector to App Menu flyout.
- Fixes the Avatar initial proportions and simplifies the look: circular, without background color, drops the chevron, adds "Signed in as..." to the dropdown menu. Also changes the first initial font to be generic `sans-serif`. Some fonts (like open sans) have uppercase glyphs (like "J") that descend below the baseline and look off-center.
- Since the Avatar dropdown now shows "Signed in as", this info in dropped from the flyout App Menu.
- Changes the Search Input colors from neutrals to transparent blacks. The grayscale text looks off when the background has a color, like in the Folwell theme. Neutral black mixes better with the bg color.
Stacked on #115 
Live on dev: …
> App Header: Move Theme Selector, Fix Avatar Proportions (stacked on #115)

- package.json
- src/api/index.ts
- src/components/SearchResultsGallery/SearchResultsGallery.vue
- src/components/SearchResultsGallery/useSlidesForMatches.ts
- src/constants/constants.ts
- src/icons/ExitFullscreenIcon.vue
- src/icons/FullscreenIcon.vue
- src/icons/index.ts
- src/pages/SearchResultsPage/SearchResultsPage.vue
- src/pages/TestPages/SlidesTestPage.vue
- src/router.ts
- src/stores/searchStore.ts
- src/types/index.ts
- yarn.lock
This adds a gallery view of search results:
- The gallery creates slides for search matches, any files within the asset (that is, any objects with a defined `fileId`), and any related assets items found in the asset's `relatedAssetCache`. 
- While adjacent results are loading asynchronously, placeholder slides will be used.  
- When the `activeSlideIndex` is within 10 of the last slide, the gallery will load more search results.
(At least) one bug that needs to be resolved: with some searches on dev, like "Test", the gallery with throw an error and the active slide index won't update properly in the main slider. I'm probably making an incorrect assumption about the shape or existence of some match result or asset data.
Currently up on dev for testing: …
> Add gallery view for search results

- src/components/AppMenu/AppMenu.vue
Drawers won't appear in app menu if a user is not logged in.
Not logged in:
Logged in:
Fixes #88
> fix: non-logged in user should not see Drawers in the menu

- src/components/AppMenu/AppMenu.vue
Fixes #89
Screenshots of 4 states below...
not logged in, and no public collections (link hidden):
not logged in, but there are public collections (link appears):
logged in, and no collections (link still appears):
logged in, and collections exist (link appears like normal):
> fix: hide collections in app menu if no collections and not logged in

- src/components/AppHeader/AppHeader.vue
- src/helpers/selectInstanceFromResponse.ts
- src/pages/HomePage/HomePage.vue
- src/stores/instanceStore.ts
- src/types/index.ts
Fixes #90
Shows search bar if `userCanSearchAndBrowse` is true, even if the user is not logged in. 
Previously, I put the `canSearchAndBrowse` property under `currentUser`. But `currentUser` may be undefined if they're not logged in, which means `currentUser?.canSearchAndBrowse` will be falsey even if `canSearchAndBrowse` is true. This PR moves the prop from `currentUser` to `instance` in the `instanceStore`.
Up on dev for testing (stacked on #89 and #88).
> fix: search bar should show up if user can search and browse

- src/components/SearchResultCard/SearchResultCard.vue
- src/helpers/displayUtils.ts
- strips any html tags out of the title on the search results card (keeps them on asset page)
- fix title link on asset page. Previously, if a user clicked on one of the title links, and the title had html, it would encode the HTML in the `querySearch`. This wouldn't show the correct result(s). Now this just strips HTML from the `querySearch`:
> fix: search results title should not show html tags

- src/pages/SearchResultsPage/SearchResultsPage.vue
- src/stores/searchStore.ts
Two updates:
- when a search completes, if the `searchStore.query` is empty, it will be set to the `searchText` returned from the search. This handles the case where a user enters a search result page directly (without typing in a query into the search input), or if the user refreshes the page. (#98 )
- When leaving the search results page, `searchStore.query` will be cleared. So the search text won't stick around as a user navigates to other pages. (#99 )
On <https://dev.elevator.umn.edu/defaultinstance/> for testing
Fixes #98
Fixes #99
> fix: search input empty on search page

- src/pages/SearchResultsPage/SearchResultsPage.vue
This fixes an issue where the results loading skeleton would show up in place of the page title if the search query was empty. Now a generic "Search Results" title will be shown:
On dev for testing:
<https://dev.elevator.umn.edu/defaultinstance/search/s/c2487d87-6bc8-40aa-8f6e-6b9dcbd84564?resultsView=grid>
> fix skeleton showing when seach query is empty

- src/api/index.ts
- src/components/AdvancedSearchForm/AdvancedSearchForm.vue
- src/components/AdvancedSearchForm/FilterByCollectionsSection.vue
- src/components/AdvancedSearchForm/FilterByFieldsSection.vue
- src/components/DropDown/DropDown.vue
- src/components/Toggle/Toggle.vue
- src/stores/instanceStore.ts
- src/stores/searchStore.ts
- src/types/index.ts
This update introduces filtering by specific text fields to advanced search. Users can now add multiple text field filters, with the choice to toggle between AND/OR boolean operators. 
While this PR covers only text field types, future PRs will expand to other types. The choice of text fields as a starting point is due to their simplicity and fewer API calls for displaying user options.
Potential search/sort fields are kept in `instanceStore`, while  `searchStore` keeps the field filters and handles creation, updates, and deletions. 
Search filters are assigned unique UUIDs to accommodate multiple filters for the same field. They are stored in a Map for faster value updates and are translated to a format suitable for the search POST request via `searchStore.searchRequestOptions`
In the …
> Advanced Search: filter by text fields

- package.json
- vite.config.ts
This resolves an issue with asset caching beyond the main js and css files using the approach outlined in the [Vite Backend Integration Guide](https://vitejs.dev/guide/backend-integration.html).
This changes vite's build step to generate a `manifest.json` file can be used by the backend for cache-busting.
> Change build to generate a `manifest.json` so that it can use hashes in file name

- src/components/Button/Button.vue
The `<Button>` component creates an `<a>`, `<RouterLink>`, or `<button>` all styled uniformly depending on the attributes passed. `to` creates a `RouterLink`, while `href` creates an anchor tag. 
The generated `RouterLink` component wouldn't have a proper href attribute though, preventing tabbing and urls showing up in the status bar. 
It was noticeable when tab-navigating through this page, for example:
This fix prevents the Button generated RouterLinks from swallowing hrefs.
On <https://dev.elevator.umn.edu/defaultinstance/> with #149 for testing.
> fix some`<Button>` component tab-ability

- src/api/index.ts
- src/components/AdvancedSearchForm/FilterByFieldsRow.vue
- src/components/AdvancedSearchForm/MultiSelectFieldOptions.vue
- src/components/CascadeSelect/CascadeSelect.stories.ts
- src/components/CascadeSelect/CascadeSelect.vue
- src/stores/searchStore.ts
- src/types/index.ts
Adds a cascade select component and multiselect field options to advanced search. Also fixes a bug where the search boolean wasn't set when we received search results.
<https://dev.elevator.umn.edu/defaultinstance/>
> Add cascading multiselect to advanced search

- package.json
- src/api/fetchers.ts
- src/api/index.ts
- src/components/AdvancedSearchForm/AdvSearchDropDown.vue
- src/components/AdvancedSearchForm/AdvancedSearchForm.vue
- src/components/AdvancedSearchForm/FilterByFieldsRow.vue
- src/components/AdvancedSearchForm/FilterByFieldsSection.vue
- src/components/AdvancedSearchForm/FilterByGlobalDateRow.vue
- src/components/AdvancedSearchForm/MultiSelectFieldOptions.vue
- src/components/AdvancedSearchForm/SelectFieldOptions.vue
- src/components/Button/Button.vue
- src/components/CascadeSelect/CascadeSelect.vue
- src/components/DropDown/DropDown.vue
- src/components/InputGroup/InputGroup.vue
- src/components/SearchBar/SearchBar.vue
- src/components/SearchBar/SearchTextInputGroup.vue
- src/constants/constants.ts
- src/helpers/parseDateString.test.ts
- src/helpers/parseDateString.ts
- src/pages/LocalLoginPage/LocalLoginPage.vue
- src/stores/instanceStore.ts
- src/stores/searchStore.ts
- src/types/index.ts
- yarn.lock
This lets a user search by `Any Date` in the advanced search.
- Any Date is a special global search field, not a specific field like other fields like "Title" or "Author". It doesn't have a real `fieldId`, it isn't returned with other fields with `getInstanceNav`, and it's values shouldn't be included with other specific fields in the search query.  
- We want it to appear like it's just another specific field filter to the user in the UI. That is, we want the user to be able to select it from the dropdown with other fields, and update it's values like other fields.
- The solution should accommodate other general fields. There's an Any Location filter too, which will need to use a similar pattern.
We keep the data for the any date filter in the searchStore in `filterBy.globalDateRange` …
> Add `Any Date` to Advanced Search

- src/__mocks__/mockSearchResults.ts
- src/components/ActiveFileViewToolbar/DownloadFileButton.vue
- src/components/ActiveFileViewToolbar/MoreFileInfoButton.vue
- src/components/Map/Map.vue
- src/components/Widget/LocationWidget/LocationItem.vue
- src/helpers/selectCurrentUserFromResponse.ts
- src/types/index.ts
This fixes some type errors found by `vue-tsc`:
- mock search results needs a widget list and a few other props to satisfy search results type
- map markers need an id
- map bounds prop can be optional
- removed `userCanSearchAndBrowse` prop from user object to satisfy type check. (This was moved from the user object to the instance object awhile back since we need this prop at the instance level to know whether to show/hide search bar even if the user isn't logged in)
> Fix some type errors

- src/components/SearchBar/SearchBar.vue
- src/pages/SearchResultsPage/SearchResultsPage.vue
- src/pages/StaticContentPage/StaticContentPage.vue
- src/router.ts
- src/stores/searchStore.ts
This fixes an issue where search filters would clear when navigating back to the search results page from an asset page.
1. Instead of always clearing the search filters when leaving the search results page, the filters when be cleared whenever arriving on a page other than the search results page or asset view page. (Some route names are added to `router.ts` to make route checking more readable.)
2. We always do a `searchStore.search` when arriving on a page. 
Previously, we would do a check if the search was already in flight, and then skip running a `searchStore.search` to prevent double search requests. The double request was caused by the search submit handler kicking off a search and then redirecting to the results page. But also arriving on the results page would also kick off a …
> Clear search filters on static pages

- src/components/SearchResultCard/SearchResultCard.vue
Fixes the chip colors and transitions on the search results card. I think this is a regression due to specificity change after Tailwind package update.
Before:
After:
> fix search result chip colors and transitions

- src/components/FeaturedAssetCard/FeaturedAssetCard.vue
- src/pages/HomePage/HomePage.vue
If the homepage has a featured asset, there can be a layout shift while page content loads.
Before the Featured Asset starts left, and then shifts right once the page content is loaded. (Cumulative layout shift: ~0.4s)
After moving the `v-if=page` from the container to the `<SanitizedHTML>` element and wrapping with a `<Transition>`, layout stops shifting. (Cumulative Layout Shift = ~0s)
<https://dev.elevator.umn.edu/defaultinstance/>
Resolves #143.
> Prevent Home Page layout shift on page load

- src/components/ActiveFileViewToolbar/MoreFileInfoButton.vue
- src/types/FileMetaDataTypes.ts
This resolves #83 where sometimes the meta data modal would be completely blank if some of the meta data is undefined.
Changes:
- Use "Unknown" in the main meta data section if metadata is nullish.
- Just show the plain json under details (previously, we were using an accordion to show details).
- use fade transition instead of skeleton on content load
This was an example of an item which previously caused issues:
<https://dev.elevator.umn.edu/defaultinstance/asset/viewAsset/575ee4c0ba98a87472f3df29>
> Fix: undefined file meta data causes More Info modal to be blank

- src/api/fetchers.ts
- src/api/index.ts
- src/components/ClickToSearchLink/ClickToSearchLink.vue
- src/components/Widget/TagWidget/TagWidget.vue
- src/helpers/displayUtils.ts
- src/stores/searchStore.ts
This resolves an issue where widgets using `<ClickToSearchLink>` would do a full page refresh on click. Now`<ClickToSearch>` will now grab the searchID when clicked, and redirect to the search. 
The Tag widget is changed to wrap `<Chip>` with `<ClickToSearch>`  rather than pass a plain href to the `<Chip>` component.
This also encodes search text in the URI, resolving an issue with some click to search text  (`Africa & Asia`).
- Complements UMN-LATIS/elevator#139
- Resolves #104
- Supersedes #180
> Fix: Widgets using `<ClickToSearchLink>` component do a full page refresh

- src/components/ActiveFileViewToolbar/ActiveFileViewToolbar.vue
This fixes an issue where the Add to Drawers button would show up for all users – whether they can add to drawers or not.  (I must have accidentally dropped the check when I moved the "Add to Drawers" button to the fileview toolbar.)
> Fix: only show add to drawers if users can add to drawers

- src/api/fetchers.ts
- src/api/index.ts
- src/components/SearchResultCard/SearchResultCard.vue
- src/components/SearchResultsGrid/SearchResultsGrid.vue
- src/components/ToastRoot/ToastRoot.vue
- src/pages/DrawerViewPage/DrawerViewPage.vue
- src/types/index.ts
This adds a remove button to the assets listed on a drawer view page so that a user can remove the asset from the drawer:
Also fixes some cache-busting issues when mutating drawers.
> Add feature: Users can remove assets from drawers from the drawer results page

- src/components/RemoveFromDrawerButton/RemoveFromDrawerButton.vue
Strips any tags from the object title within the confirm modal.
Resolves #189
> Fix tags showing up in confirm modal

- package.json
- src/api/fetchers.ts
- src/api/index.ts
- src/components/MediaCard/MediaCard.vue
- src/components/RemoveFromDrawerButton/RemoveFromDrawerButton.vue
- src/components/SearchResultCard/SearchResultCard.vue
- src/components/SearchResultRow/SearchResultRow.vue
- src/constants/constants.ts
- src/icons/DragIcon.vue
- src/icons/index.ts
- src/pages/DrawerViewPage/DrawerItemsGrid.vue
- src/pages/DrawerViewPage/DrawerItemsList.vue
- src/pages/DrawerViewPage/DrawerViewPage.vue
- src/router.ts
- src/stores/drawerStore.ts
- src/types/index.ts
- yarn.lock
This adds sorting to drawers, including drag-and-drop custom sort. VueDraggable is added as a dependency for drag and drop magic.
Drawer browsing and sorting is very similar to normal search, but just different enough that I often just copied search components and then modified them slightly to work with drawers. Which is to say that there's a bit of duplicate code here that could probably use a refactor in the future.
> add custom sort type

- src/api/fetchers.ts
- src/stores/drawerStore.ts
A few updates to the drawer store and api:
- In `drawerStore.setDrawerItems`, if the order of objectIds doesn't change, we skip making an API request to `api.setSortOrder`
-  removes`/true` on the `setSortOrder` api request since the endpoint now always returns json. See: UMN-LATIS/elevator#144
- simplified `drawerStore.removeAssetFromDrawer` to use `this` less, similar to `drawerStore.setDrawerItems`.
TS's flow analysis will show errors that `this.drawerRecords[x].contents` may be undefined (even after we check that it's defined) presumably because the `this` object could be potentially mutated elsewhere in way TS can't follow. By creating a reference with `const drawer = this.drawerRecords[x]`, we can  skip the non-null assertion with the `!` in `this.drawerRecords[x].contents!.matches` …
> updates to drawer store and api requests

- src/stores/searchStore.ts
This fixes a regression (introduced in 17fdc62) where the results on the search page don't update after a user changes the sort order. After updating the searchStore's state with the new sort option, we need to get first get the new searchId, and then use the searchId to grab the results.
Previously, we weren't getting a new searchId after the sort changes.
> fix: search results don't update when sort changes

- src/api/fetchers.ts
- src/api/index.ts
- src/components/AuthDropDown/AuthDropDown.vue
- src/main.ts
- src/pages/LocalLoginPage/LocalLoginPage.vue
- src/pages/LogoutPage/LogoutPage.vue
- src/router.ts
- src/stores/resetAllStores.ts
- src/stores/resetStorePlugin.ts
Resolves:
- #195 
**Before:** After logging in, a guest user would see no drawers even if they had access to drawer. A refresh was required to see the drawers.
**After:** After logging in, a guest user will see their drawers without needing to refresh.
This issue was caused by stale app state that wasn't refreshed after a user logged in. This PR now resets the Pinia stores and clears any cached api responses when a user logs in or logs out.
The PR complements a forthcoming change to [UMN-LATIS/elevator](https://github.com/UMN-LATIS/elevator) which will return a json response from the /logout endpoint rather than a redirect.
> Reset app stores and api cache after login/logout

- src/components/AppFooter/AppFooter.vue
- src/components/AppFooter/exampleFooterContent.html
- src/layouts/DefaultLayout.vue
- src/pages/HomePage/HomePage.vue
- src/pages/StaticContentPage/StaticContentPage.vue
- src/stores/instanceStore.ts
- src/types/index.ts
- tailwind.config.js
This adds support for the custom footer content in elevator. The footer will only show on the home page and static content pages.
It's likely that existing custom footer content will need a little scrubbing to remove old CSS classes and formatting to better fit with the updated ui. (I'd be happy to to help current instances do this). I've added the cleaned example footer content in `exampleFooterContent.html`, which could be used as a base for updates.
> Add support for custom footer content

- src/components/MoreLikeThis/MoreLikeThis.vue
- src/components/Widget/TextAreaWidget/TextAreaItem.vue
- src/config.ts
- src/types/index.ts
This complements UMN-LATIS/elevator#147, allowing an instance admin to configure the height of it's collapsed textarea widget.
The `AppConfig` is updated to use the value on `instance.textAreaItem.defaultTextTruncationHeight` to override the default height of ~3lines or 72px (16px base font size * 1.5 line-height * 3 lines).
Additionally, this PR moves `moreLikeThis.maxInlineResults  to be within the `instance` config object as well since it seems like a similar component-level instance setting.
Setting `defaultTextTruncationHeight` to `24`:
Setting `defaultTextTruncationHeight` to `72`:
> Make the height of the collapsed TextArea widget configurable

- src/router.ts
`document.querySelector` will throw if `to.hash` isn't valid. e.g. if the id begins with a number instead of a letter. 
This switches to `getElementById` and only attempts the scrollTo behavior if the element is found.
Resolves #208
> fix invalid hash id error

- src/pages/SearchResultsPage/SearchResultsPage.vue
watch the search store status and only attempt to scroll into view if we're no longer fetching
Resolves #209
> fix: object doesn't scroll into view

- src/components/Widget/TagWidget/TagWidget.vue
Fixes tag wrapping in the TagWidget.
Before:
After:
> fix: tags should wrap

- src/components/Accordion/Accordion.vue
- src/components/RemoveFromDrawerButton/RemoveFromDrawerButton.vue
- src/components/SearchResultCard/SearchResultCard.vue
- src/components/SearchResultRow/SearchResultRow.vue
- src/components/SearchResultsGallery/useSlidesForMatches.ts
- src/helpers/displayUtils.ts
Fixes #217 
Renamed`stripTags` to `convertHtmlToText` since the function does more than just stripping tags. Some files touched by the name change.
> Convert any html in accordion label to text

- src/components/Widget/RelatedAssetWidget/RelatedAssetWidget.vue
Makes related asset links flow as a column to improve readability:
Resolves #215
> make related asset links flow as col

- src/pages/AllCollectionsPage/AllCollectionsPage.vue
If a static page named "Collection Page" exists, the content will be added to the All Collections page (below the word collections and above the list of collections.
https://dev.elevator.umn.edu/defaultinstance/search/listCollections
Fixes #223
> Add Collection Page content to collections page

- src/components/SanitizedHTML/SanitizedHTML.vue
This permits embedded `<iframe>` tags within sanitized html content. Fixes #225.
See: https://dev.elevator.umn.edu/defaultinstance/page/view/21
> Support pages with iframes

- src/components/Widget/RelatedAssetWidget/RelatedAssetWidget.vue
- src/components/Widget/RelatedAssetWidget/ThumbnailRelatedAssetWidgetItem.vue
- src/components/Widget/UploadWidget/UploadWidget.vue
This adds keyboard shortcuts for navigating between related assets or uploads on an asset view page. When viewing a file or object that's active, pressing left or right will move to the next/prev item within the group.
> navigate to next file or related asset with left/right keypresses

- src/components/SearchBar/SearchTextInputGroup.vue
Remove hiding of search button on smaller screen. Changes `type` and `inputmode` on input element, so that the mobile device virtual keyboard shows a non-default button.
> show search button on mobile

- src/components/Tabs/Tabs.vue
This adding a stable custom CSS class on each tab button, so that an admin could include custom CSS to hide search tabs like:
```css
.tab-button--timeline { display: none; }
```
This complements https://github.com/UMN-LATIS/elevator/pull/150, which adds the custom CSS to the vue template.
Closes #144
> support hiding tab buttons with custom css

- src/components/AppFooter/AppFooter.vue
- src/components/AppHeader/AppHeader.vue
- src/components/CustomAppHeader/CustomAppHeader.vue
- src/components/SanitizedHTML/SanitizedHTML.vue
- src/layouts/DefaultLayout.vue
- src/pages/HomePage/HomePage.vue
- src/pages/StaticContentPage/StaticContentPage.vue
- src/stores/instanceStore.ts
- src/types/index.ts
This complements https://github.com/UMN-LATIS/elevator/pull/151 and includes a custom header on the home page or static pages (if defined). Fixes #231.
> Include custom app header

- src/components/Widget/RelatedAssetWidget/AccordionRelatedAssetWidgetItem.vue
- src/components/Widget/RelatedAssetWidget/CollapsedInlineRelatedAssetWidgetItem.vue
- src/components/Widget/RelatedAssetWidget/LinkedRelatedAssetWidgetItem.vue
This fixes #234 : Related Asset Cache Titles aren't being used in some cases 
The suggestion issue was correct: The <RelatedAssetWidget> passes `assetCacheItem`, not `assetCache` to child components, but some of those children were expecting an `assetCache` prop. This updates to use `assetCacheItem`.
(Aside: it'd be nice if one could declare an interface for dynamic `<component>`s, so the linter would check if there's a prop mismatch like this... maybe there is?)
> fix: related asset titles not being used in some cases.

- src/components/Widget/LocationWidget/LocationItem.vue
Using the `inline` variant of Tuple causes will crop off some of the lng data and the accordion chevron because "Longitude" and "Latitude" are a bit long.
This:
- abbreviates with "Lng" and "Lat"
- removes unnecessary right padding that's causing a flexbox overflow with the chevron.
- adds flex-wrap, just in cause some screensizes or fonts or whatever still cause an overflow.
> fix: lng lat label overflow

- src/components/Map/Map.vue
- src/components/MapMarker/MapMarker.vue
- src/components/SearchResultsMap/SearchResultsMap.vue
- src/types/index.ts
This resolves #243, an issue where only a subset of results with locations where showing on the map search results page.
The issue was the check for `primaryHandlerId`: when a search result had no `primaryHandlerId`, the loop skipped rendering the map marker.
A `primaryHandlerId` is needed for rendering a thumbURL, but not every match will have a thumbnail  (assets that are  "metadata only" won't have a `primaryHandlerId`, but they will still have a location). 
This PR allows `imgSrc` to be null, and instead skips any matches without locations.
An additional issue was uncovered once all map markers started loading: `Maximum recursive updates exceeded.`
This was caused by a conflict between the `watch`ers on `markers` (vue api) and the event listener for `styledata` changes (mapbox api). …
> fix: map marker not rendering if no primaryHandlerId

- src/components/SearchResultsSortSelect/SearchResultsSortSelect.vue
- src/pages/SearchResultsPage/SearchResultsPage.vue
Fixes #244.
Previously, the add results to drawer button was aligned vertically center with the search results page header.  This would be difficult to find and jump around when a page had a large custom header.  This moves the button to the results count/sort bar, so that it's in a consistent position regardless of header size.
> fix: move add results to drawer button to results/sort bar

- .prettierrc.json
- public/img/warning-icon.svg
- src/css/app.css
- src/pages/HomePage/HomePage.vue
- src/pages/StaticContentPage/StaticContentPage.vue
- Adds layout classes that content editors can use on static pages if they want to add some layout. These are namespaced under `el-` to keep these abstracted away from a specific framework (tailwind, bootstrap). I chose a BEM approach where multiple classes can be applied like `el-grid el-grid--2/3-1/3` for a 2 column layout with first col 2/3 width and second 1/3 width.
- NIBSDA static page content has been prepped for migration to new ui. They're available for review on https://dev.elevator.umn.edu/defaultinstance/. Content is also saved in [its own private repo](https://github.com/UMN-LATIS/nibsda-static-page-content) with a few notes. Principally, the content just needs to use semantic markup (`p` instead of `h5`), remove inline styles, and change to `el-` classes where advanced …
> Add some helpers for editing static content pages

- src/api/fetchers.ts
- src/api/index.ts
- src/components/ShareButton/ShareButton.vue
- src/components/ShareFileButton/ShareFileButton.vue
- src/components/SkeletonCard/SkeletonCard.vue
- src/pages/SearchResultsEmbedPage/SearchResultsEmbedPage.vue
- src/pages/SearchResultsPage/SearchResultsPage.vue
- src/router.ts
- src/stores/searchStore.ts
- adds an share button to map, gallery, and timeline tabs of search results page
- adds route for embed views
Closes #240 
Question: How do we handle the number of results loaded? Should there be a load more button on the embed views? Or some way to ensure the same results are loaded for embed?
> Make search results map, gallery, and timeline view embeddable

- src/components/CustomAppHeader/CustomAppHeader.vue
adds an exception to allow `<link>` in custom headers, so that external stylesheets can be linked.
Resolves UMN header rendering issue in https://github.com/UMN-LATIS/elevator/issues/152
Before
After
> allow link tag in custom header

- src/config.ts
- src/router.ts
- src/types/index.ts
This allows an admin to set a custom home page route, for example `/search/listCollections`.  Users will be redirected to this route when set.
Either absolute paths or full urls can be used. If a full url is used, the base url will be stripped so that the redirect becomes an absolute path.( e.g. `https://dev.elevator.umn.edu/defaultinstance/search/listCollections` -> `/search/listCollections`)
If the redirect is set to null or `/` or the base path, the default home page will be used.
This complements a forthcoming PR to elevator, which adds the custom home page config option to the instance settings.
On dev for testing: <https://dev.elevator.umn.edu/defaultinstance>. Currently the custom home route is set to  `/search/listCollections`.
> add config option for custom home route

- src/pages/ExcerptViewPage/ExcerptViewPage.vue
Fixes https://github.com/UMN-LATIS/elevator-ui/issues/262
Excerpt link is used instead of asset link:
This complements a forthcoming PR in elevator.
> use excerpt share url on excerpt page

- src/components/AppFooter/AppFooter.vue
- src/pages/HomePage/HomePage.vue
- removes extra classes on `app-footer` as they may conflict with custom instance footers and will need to be overridden.
- moves `<AppFooter>` from `<main>` to `<footer>` in the `DefaultLayout`
- fixes #264. In Safari, sometimes grid items would overflow the grid container if `grid-template-rows` isn't explicitly set.
> app footer fixes

- src/components/SearchBar/SearchTextInputGroup.vue
fixes #246
There's probably better ways to work with the search input type, but the easiest fix seems to just use the default text input type.
I'll push to dev once #269 is merged.
> fix extra clear input button on search

- tailwind.config.js
With this, users can avoid all the default prose styles if they wish to customize static content pages. 
for example:
```html
<div class="custom-homepage not-prose">
...
</div>
```
> add `not-prose` to safe list as escape hatch for static page styles

- src/helpers/timelineHelpers.ts
use config path instead of hardcoded `defaultinstance`
fixes #275
> fix: asset links not using correct instance in timeline tab

- src/components/AppMenu/AdminNavSection.vue
> append searchId as hash to export as csv menu link

- src/components/DownloadFileButton/DownloadFileButton.vue
Fixes #291
When the download link is clicked in safari, the browser cancels any in flight requests – maybe as it prepares to change to a new page? 
This causes some api requests to fail after the download link click. A 499 is observed on the server.
There are a few solutions to this:
- adding a `download` attr to the link
- changing to a button, and invoking the download url with JS
- open download in a new blank window
I went with the `download` attr as it seemed to be the simplest, but there could be edge cases I missed.
> fix: safari error when downloading file

- index.html
- src/helpers/useAnalytics.ts
An alternative approach if `noop` is too "clever" (in a bad way).
> fix: white screen when analytics key undefined (early return)

- src/components/DropDown/DropDown.vue
- src/components/DropDown/DropDownItem.vue
- src/components/Tuple/Tuple.vue
- src/components/Widget/UploadWidget/UploadWidget.vue
- src/components/Widget/Widget.vue
- src/types/index.ts
Closes https://github.com/UMN-LATIS/elevator-ui/issues/282
This supersedes #293 
- Adds a "more actions" menu to the Upload Widget component to allow users to download all derivatives (or originals, if permitted).
- Some browsers (safari) it seems will abort any in-flight download requests if a response hasn't been returned from the server, so an artificial timeout is added ~2s to wait for the server to respond. (The download doesn't need to finish within 2s, it just needs to start within that time or an error will be thrown).
- To determine whether or not a user can download originals, we need to get file info for the first download. Since using the download all feature is rare, we avoid doing with every upload widget rendering. Instead, the permission check will happen once the user …
> Add dropdown menu options for downloading all assets in upload widget

- src/pages/SearchResultsPage/SearchResultsPage.vue
- src/stores/searchStore.ts
Resolves #298 
Sometimes, the `sort` field in UI wouldn't match the search results. For example, if you typed "test" in the search input. The results returned would have `searchEntry.sort: 0` (best match), but the search selector would show `Default Title` 
The cause:
- On initial page load, the query is empty as the page waits for the search results to load.
- Previously, we had logic to set an initial sort state. It would use a query param (if one existed), or "Best Match", or – and this is where the problem is – it would use "Default Title" if the search was blank (i.e. we were asking for all results).
- Because the query was empty on page load (since data wasn't loaded), the initial sort was "Default Title"
- THEN – and this is error #2 – we were not properly updating the sort  in …
> fix: search sort sometimes listed incorrectly

- src/api/fetchers.ts
- src/components/Widget/UploadWidget/UploadWidget.vue
- src/stores/searchStore.ts
- src/types/FileDownloadTypes.ts
- src/types/index.ts
Previously, Download All would skip some trying to download some assets based on the file type (e.g. "dicom", "tiled"). This updates to use a `downloadable` prop passed back with download info. Files must have at least one `downloadable` version for a download to be attempted.
on dev for testing.
> use new `downloadable` prop with Download All

- src/components/AppLogoMark/AppLogoMark.vue
- src/components/Modal/Modal.vue
- src/components/ThemeSelector/ThemeSelector.vue
- src/css/themes/st-thomas.css
Adds a theme with St. Thomas brand colors and type (Lato). I'm sure more things could be purple, but this seems like a good start.
On dev for testing.
`.env` will need `st-thomas` theme added the `AVAILABLE_THEMES` array (currently manually set on dev).
> add St Thomas theme

- src/pages/AllCollectionsPage/AllCollectionsPage.vue
- src/pages/AllDrawersPage/AllDrawersPage.vue
- src/pages/HomePage/HomePage.vue
- src/pages/StaticContentPage/StaticContentPage.vue
- src/stores/instanceStore.ts
- adds enum for different custom header modes
- render footer on collection and drawers page if mode allows
- fix static page: only render on "always" mode
- fix home page: do not render if "never" mode
On dev for testing
> fix: showing custom header and footer

- src/pages/CreateOrEditAssetPage/EditWidget/EditWidgetLayout.vue
The set primary background would show up on hover. This make the full button invisible, not just the star. 
We use invisible instead of hidden to keep the layout consistent between widgets.
> fix(EditWidgetPage): make set primary hidden when there's only one item

- src/components/Widget/RelatedAssetWidget/AccordionRelatedAssetWidgetItem.vue
- src/components/Widget/RelatedAssetWidget/CollapsedInlineRelatedAssetWidgetItem.vue
- src/components/Widget/RelatedAssetWidget/LinkedRelatedAssetWidgetItem.vue
- src/components/Widget/RelatedAssetWidget/RelatedAssetWidget.vue
- src/components/Widget/RelatedAssetWidget/ThumbnailRelatedAssetWidgetItem.vue
- src/components/Widget/RelatedAssetWidget/getTitleFromCacheItem.ts
Show related asset label if `showLabel` is true. 
Details:
- Label will NOT show if it matches the title. (assumed this is the desired behavior, but let me know).
- moves title calculation to the parent RelatedAssetWidget component and then passes it down to child components.
- In parent, `cacheItem` and `title` are now part of each `contentsWithAssetId` object.
On dev for testing.
Resolves #317
> show related asset label in parens if configured

- mock-server/routes/assets.ts
- src/components/SelectGroup/SelectGroup.vue
- src/pages/CreateOrEditAssetPage/CreateOrEditAssetPage.vue
- src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetEditor.ts
- src/types/index.ts
- Fixes an issue where the collectionId would not be properly initialized when loading the EditAsset page.
- updates `<SelectGroup>` component to permit numeric ids instead of just strings.
- then retypes collectionId and templateId as number | null, and then adds stronger types to the asset editor to help catch mismatches.
- separate asset initialization for new and saved assets. Now the watcher will auto-initialize savedAssets once the data is ready, while the `initNewAsset()` can be invoked on the page when the user clicks continue.
- fixes an issue with the mock server, where collectionId and templateId were added as strings instead of ints to the mockDB, causing tests to fail.
on dev for testing
> fix blank `collectionId` in select when loading edit page

- src/pages/CreateOrEditAssetPage/CreateOrEditAssetPage.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditUploadWidget/EditUploadWidget.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditUploadWidget/EditUploadWidgetItem.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditUploadWidget/FileUploader.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditWidgetLayout.vue
- src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetEditor.ts
- src/types/index.ts
- tests/e2e/multiple-file-upload.spec.ts
- tests/e2e/upload-widget.spec.ts
This supersedes #321 
- saves uploads when the begin, not just when they complete to avoid orphaned uploads.
- debounce save emits to cut down on requests (~2s, max: 5s)
- adds test for uploading multiple assets
- fixes a warning when submitting form (handler was attached to button, not the form's submit event)
- block arcgis requests when testing
- refactor some useAssetEditor methods to use promises instead of callbacks
- renames some functions so they're more distinct from in-component handler names
> Debounce asset editor saves

- src/pages/CreateOrEditAssetPage/InlineCreateOrEditAssetPage.vue
- src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetEditor.ts
Checks if the inline related asset form is blank, and if so – we'll skip saving to avoid creating a blank asset.
One note: we're considering unchecked checkbox widgets as content, so if an inline asset form contains them, the asset will appear non-blank and save.
This also removes a check for `assetEditor.hasAssetChanged` since the value is sometimes off. So, we save the inline asset regardless of whether a change is detected or not (provided it has _some_ content).
> fix: don't create inline related asset if no content

- src/pages/CreateOrEditAssetPage/CreateOrEditAssetPage.vue
- src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetEditor.ts
After saving, the primary file handler id may need to be updated. This fetches the asset after saving, and then updates primary file hander id (and a few other fields).
> fix: update primary file handler id after save

- src/constants/constants.ts
- src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetValidation.ts
- src/types/index.ts
- Create useAssetValidation composable with debounced validation.
This is part of a series of PRs, which refactor asset validation. 
This is a stage-setting PR, with no intended change to functionality.
Asset editor validation state is needed in several places throughout the create/edit pages:
- Save button: to determine if an asset is savable and which error messages to show.
- Sidebar Table of Contents: to show iconography about widget validation state
- widget container component: again, to show iconography about widget validation state
- widget content item: individual field errors
Currently, we check for missing required fields and if content is blank or not. But, some components have more nuanced validation, like (dates need to be valid and end dates need to be after start dates). …
> add `useAssetValidation` composable for centralized asset editor validation

- src/constants/constants.ts
- src/pages/CreateOrEditAssetPage/CreateOrEditAssetPage.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditDateWidget.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditDateWidgetContentItem.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditWidgetLayout.vue
- src/pages/CreateOrEditAssetPage/InlineCreateOrEditAssetPage.vue
- src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetValidation.test.ts
- src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetValidation.ts
- src/types/index.ts
- updates the date widget and the widget container to use the `useAssetValidation`
- fixes an error when the DateWidgetContentItem is using a non-existent `range` prop.
- clears end date if user changes from `range` to `moment`.
> validate start and end dates in date widget (stacked on #348)

- src/api/fetchers.ts
- src/pages/CreateOrEditAssetPage/EditWidget/EditRelatedAssetWidget/EditRelatedAssetContentItem.vue
- src/queries/queryKeys.ts
- src/queries/useSearchRelatedAssetsQuery.ts
This fixes an issue where related asset search was not using `matchAgainst` in the widget definition to scope the research to particular templates.
> fix: related asset search scoping on CreateOrEditAssetPage

- src/pages/CreateOrEditAssetPage/EditWidget/EditUploadWidget/FileUploader.vue
Some of uppy's z-indices are inconsistent and interfere with our modal z-indices during errors. 
This PR creates a new stacking context, so that uppy's z-index doesn't trump our ui z-index.
Before:
After
> fix z-index conflicts between uppy and error modal

- src/components/InputGroup/InputGroup.vue
- src/components/Tuple/Tuple.vue
- src/css/themes/default.css
- src/pages/CreateOrEditAssetPage/CreateOrEditAssetPage.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditUploadWidget/EditUploadWidgetItem.vue
- src/pages/CreateOrEditAssetPage/EditWidget/EditUploadWidget/EditUploadWidgetItemSidecars.vue
- add source file name and download button to upload widget in asset editor
- fixes inconsistencies between tuple label weights and input label weights
Also tweak styles in the expandable file details section to align. The "View Logs" button in file details now is similar to the new "Download" button.
On dev
Closes #371
> update upload widget in asset editor with download link

- mock-server/server.ts
- src/api/fetchers.ts
- src/api/index.ts
- src/components/AssetDetailsPanel/AssetDetailsPanel.vue
- src/components/ErrorModal/ErrorModal.vue
- src/components/ObjectViewer/ObjectViewer.vue
- src/components/WidgetList/WidgetList.vue
- src/helpers/useAsset.ts
- src/pages/AssetViewPage/AssetView.vue
- src/stores/assetStore.ts
This resolves an issue where users may not be able to view some related assets because server-side cannot determine permissions correctly with the parent asset id. Without this, we won't be able to load the related asset embedded in the object viewer, or get data about the asset from `viewAsset`.
Changes:
- adds an optional `parentAssetId` parameter to api functions that get asset.
- passes `parentAssetId` prop to `<ObjectViewer>` and `<AssetDetails>` components.
- updates assetStore to pass the active assetId to api functions as `parentAssetId`.
- updates `<WidgetList>` to get parentAssetId from the asset store. (I'm pretty sure this is okay, but we could run into issues if WidgetList is ever used without
This PR complements a forthcoming PR for elevator.
On dev for testing.
> fix: related asset view permission issue b/c of missing parent id
