UMN-LATIS/elevator-ui

src/components/MediaCard/MediaCard.stories.ts, src/components/MediaCard/MediaCard.vue, src/components/SearchResultItem/SearchResultItem.vue, src/components/Tuple/Tuple.vue
=> Add style to Search Result Card

src/__mocks__/mockAsset.ts, src/__mocks__/mockTemplate.ts, src/components/Widget/MultiSelectWidget/MultiSelectItem.vue
adjust mock multiselect asset to exercise our weird space handling on the curator side. Fix bug that didnt' work when categories had spaces. Fixes #34
=> Fix multi select rendering error

src/api/index.ts
=> Add storeOnly flag to initial searchResults call

.env.example, README.md
- add instructions for bootstrapping a local dev environment
- notes on building ui 
- updates the `.env.example`
=> add dev and build instructions

src/api/index.ts, src/components/AuthDropDown/AuthDropDown.vue, src/components/InputGroup/InputGroup.vue, src/css/app.css, src/icons/EyeIcon.vue, src/icons/EyeOffIcon.vue, src/icons/index.ts, src/main.ts, src/pages/LocalLoginPage/LocalLoginPage.vue, src/router.ts, src/types/index.ts
Adds page for logging in guest users.
- Login button is disabled if there's no username or password
- errors will be displayed if auth fails
- User will be redirected to previous page on login
- A show/hide password button is included (like previous login form)
- link to University Login will show under guest login button (if available)
On <https://dev.elevator.umn.edu/defaultinstance/> for testing.
Closes #91
=> Add Login for Guest Users page.

src/pages/HomePage/SignInRequiredNotice.vue
use router link instead of href
=> use router link for "Sign In Required" notification Guest Login

src/layouts/DefaultLayout.vue, src/pages/HomePage/HomePage.vue, src/pages/StaticContentPage/StaticContentPage.vue
=> Extend content area to bottom on static pages

src/components/AdvancedSearchForm/AdvancedSearchForm.vue, src/components/AdvancedSearchForm/FilterByCollectionsSection.vue, src/components/AppHeader/AppHeader.vue, src/components/AppMenuButton/AppMenuButton.vue, src/components/Button/Button.vue, src/components/DropDown/DropDown.vue, src/components/DropDown/DropDownItem.vue, src/components/InputGroup/InputGroup.vue, src/components/KeyboardShortcut/KeyboardShortcut.vue, src/components/SearchBar/SearchBar.vue, src/components/SearchBar/SearchTextInputGroup.vue, src/components/TransitionFade/TransitionFade.vue, src/css/themes/default.css, src/helpers/collectionHelpers.ts, src/helpers/pluralize.test.ts, src/helpers/pluralize.ts, src/icons/SpinnerIcon.vue, src/icons/VerticalDotsIcon.vue, src/icons/index.ts, src/pages/SearchResultsPage/SearchResultsPage.vue, src/stores/instanceStore.ts, src/stores/searchStore.ts
This adds an advanced search modal, allowing users to filter results by collections (other filters forthcoming in future PRs).
Latest on <https://dev.elevator.umn.edu/defaultinstance> for review
=> Add advanced search within collections

src/components/AdvancedSearchForm/FilterByFieldsSection.vue, src/css/app.css, src/stores/searchStore.ts
=> Add fuzzy search toggle to advanced search field filters

src/components/SkipNavLink/SkipNavLink.vue, src/layouts/DefaultLayout.vue
This adds a skipnav link that will be appear when tabbing through the interface. 
SkipNav CSS from [A11y Project](https://github.com/a11yproject/a11yproject.com) (APLv2 license) with some modification.
=> Add a skipnav link to default layout

src/App.vue, src/components/AdvancedSearchForm/AdvSearchDropDown.vue, src/components/AdvancedSearchForm/AdvSearchDropDownItem.vue, src/components/AdvancedSearchForm/FilterByCollectionsSection.vue, src/components/AdvancedSearchForm/FilterByFieldsSection.vue, src/components/Button/Button.vue, src/components/DropDown/DropDown.vue, src/components/ThemeSelector/ThemeSelector.vue, src/css/themes/default.css, src/helpers/useTheming.ts, src/layouts/DefaultLayout.vue
- sets initial theme on app mount, which fixes an issue where the theme wouldn't be set until until the app menu is opened
- reduce the visual hierarchy of dropdown "Add" menus in the advanced search
- Fix column height on home page so that it stretches the full page. (A regression after adding the skipnav link and wrapping the main content in a <main> element).
<https://dev.elevator.umn.edu/defaultinstance/>
=> load theme on app mount and visual fixes for advanced search

src/components/AdvancedSearchForm/AdvancedSearchForm.vue, src/components/AdvancedSearchForm/FilterByFieldsSection.vue, src/components/Toggle/Toggle.vue, src/stores/searchStore.ts, src/types/index.ts
=> add toggle for including hidden assets

src/api/fetchers.ts, src/api/index.ts, src/components/AppMenu/AppMenu.vue, src/components/MapMarker/MapMarker.vue, src/components/ResultsCount/ResultsCount.vue, src/pages/AllDrawersPage/AllDrawersPage.vue, src/pages/AllDrawersPage/DrawerItem.vue, src/pages/DrawerViewPage/DrawerViewPage.vue, src/pages/SearchResultsPage/SearchResultsPage.vue, src/router.ts, src/stores/searchStore.ts, src/types/index.ts
This adds pages for viewing the list of drawers and individual drawer contents.
Closes:
- #164
- #166 
On <https://dev.elevator.umn.edu/defaultinstance> for testing
=> List all drawers and view drawer contents

src/components/MoreLikeThis/MoreLikeThis.vue, src/pages/AssetViewPage/MetaDataOnlyView.vue
=> Reduce the size of `<MoreLikeThis>` on metadata only pages

src/components/Notification/Notification.vue, src/pages/HomePage/SignInRequiredNotice.vue
=> fix padding on notification

src/api/fetchers.ts
This fixes an issue where a user would see the Login Required modal on the guest login page if their login attempt failed, rather than seeing the normal invalid username/password message in the login form.
This regression was caused by adding the axios interceptors for handling errors. When the auth check fails, axios throws an 401 AxiosError which the interceptor catches and handles, triggering the modal. This is correct on most pages, but on a login page where authentication attempts commonly fail, we don't want this.
To fix this, we modify the `loginAsGuest` api method to use the `skipErrorNotifications` custom config, which causes the response to skip the interceptor so that we can handle the 401 error ourselves.
=> fix regression: on local login page invalid credentials triggers modal instead of showing error in login form

src/components/MediaCard/MediaCard.vue, src/components/SearchResultCard/SearchResultCard.vue
The search result card was missing outline and background color when focussed:
=> fix search result card focus state

src/components/ThumbnailImage/ThumbnailImage.vue, src/components/Widget/RelatedAssetWidget/ThumbnailRelatedAssetWidgetItem.vue, src/components/Widget/UploadWidget/UploadWidget.vue
Upload Widget (using file description):
Related Asset (using title):
Resolves #218
=> Add title or file description below Related Asset or Upload Widget thumbnails

src/components/AppFooter/AppFooter.vue, src/pages/HomePage/HomePage.vue
Similar to legacy interface, add some content to the main homepage area if there's no homepage content:
=> Add instance name to empty homepage

src/api/fetchers.ts, src/api/index.ts, src/pages/SearchResultsPage/DidYouMeanSuggestions.vue, src/pages/SearchResultsPage/SearchResultsPage.vue, src/stores/searchStore.ts
=> Add "Did you Mean" suggestions to search results page

src/router.ts
=> fix: don't scroll if only the query string changes

src/layouts/NoScrollLayout.vue, src/pages/AllCollectionsPage/AllCollectionsPage.vue, src/pages/AllDrawersPage/AllDrawersPage.vue, src/pages/DrawerViewPage/DrawerViewPage.vue, src/pages/ExcerptViewPage/ExcerptViewPage.vue, src/pages/HomePage/HomePage.vue, src/pages/LocalLoginPage/LocalLoginPage.vue, src/pages/SearchResultsPage/SearchResultsPage.vue, src/pages/StaticContentPage/StaticContentPage.vue, src/stores/instanceStore.ts, src/types/index.ts
knocked this out during a meeting, but happy to have @jxjj refactor if it uglifies the codebase too much.
=> make custom header mode configurable

src/components/AppLogoMark/AppLogoMark.vue, src/components/SearchBar/SearchBar.vue
Handles long app names better by adding a min-width to the advanced search and a max-width to app-name.
https://github.com/user-attachments/assets/1bd2ffd3-19b9-4684-b48e-1dd8f1c3912c
not yet on dev
=> better handling of long app names

src/__mocks__/mockSearchResults.ts, src/components/AdvancedSearchForm/AdvancedSearchForm.vue, src/stores/searchStore.ts, src/types/index.ts
=> add a boolean toggle to expose some ES functionality

src/components/Widget/UploadWidget/UploadWidget.vue
=> only show download all when mult files

src/pages/CreateOrEditAssetPage/CreateOrEditAssetPage.vue
The user gets prompt when leaving a blank addAsset page, which is annoying. This:
- moves the check for whether or not the page has changed back to the router guard to make it more explicit and not run on every compute. 
- resolves an issue where changes for enabling the `Save` button wouldn't be detected (issue caught by a failing test)
=> don't prompt user when leaving create asset page that's blank

src/pages/CreateOrEditAssetPage/EditWidget/EditRelatedAssetWidgetContentItem.vue
=> fix: related asset combobox max height

src/api/fetchers.ts
AWS s3 uploadId's can begin with a dot. This is an issue because the backend is set to deny any paths with dir/file containing a leading dot.
Escaping with `%2E` doesn't work  in Chrome (the browser will helpfully translate it back to a `.`).
So, we just replace with a `__DOT__`. And translate back in the s3 controller on the backend.
=> fix leading dot in upload id

src/pages/CreateOrEditAssetPage/EditWidget/EditUploadWidget/EditUploadWidget.vue
Hides uploads that aren't complete yet.
=> fix: in-progress uploads show in widget list

src/constants/constants.ts, src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetValidation.test.ts, src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetValidation.ts, src/types/index.ts
Add tests for useAssetValidation composable
=> add tests for useAssetValidation composable (stacked on #347)

src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetEditor.ts
=> Clear "regenerate" checkbox after save

src/components/Tuple/Tuple.vue, src/pages/CreateOrEditAssetPage/EditAssetForm/EditAssetFormSidebar.vue, src/pages/CreateOrEditAssetPage/TableOfContents/TableOfContents.vue, src/pages/CreateOrEditAssetPage/useAssetEditor/useAssetEditor.ts
=> Add assetId and last modified date to sidebar

package.json, src/components/TextEditor/TextEditor.vue, yarn.lock
- Add 3rd party HTMLEditButton module for quill.
- fixes wonky layout issues and aligns styles better with our app
On dev.
Fixes #367
https://github.com/user-attachments/assets/ad08728f-639c-49d5-8d55-afdd57532768
=> Add HTML editing
